#ifndef TOKEN_CONSTANTS_HPP
#define TOKEN_CONSTANTS_HPP

#include <string>
#include <unordered_map>

namespace lexer {

    enum LexTokenType {
        TOK_BOOL_LITERAL,
        TOK_INT_LITERAL,
        TOK_FLOAT_LITERAL,
        TOK_CHAR_LITERAL,
        TOK_STRING_LITERAL,
        TOK_ADDITIVE_OP,
        TOK_EXPONENTIATION_OP,
        TOK_INCREMENT_OP,
        TOK_MULTIPLICATIVE_OP,
        TOK_RELATIONAL_OP,
        TOK_THREE_WAY_OP,
        TOK_EQUALITY_OP,
        TOK_LOGICAL_AND_OP,
        TOK_LOGICAL_OR_OP,
        TOK_NOT,
        TOK_VOID_TYPE,
        TOK_BOOL_TYPE,
        TOK_INT_TYPE,
        TOK_FLOAT_TYPE,
        TOK_CHAR_TYPE,
        TOK_STRING_TYPE,
        TOK_ANY_TYPE,
        TOK_FUNCTION_TYPE,
        TOK_TYPEOF,
        TOK_TYPEID,
        TOK_REFID,
        TOK_USING,
        TOK_ENUM,
        TOK_NAMESPACE,
        TOK_CONST,
        TOK_VAR,
        TOK_REF,
        TOK_UNREF,
        TOK_STRUCT,
        TOK_FUN,
        TOK_NULL,
        TOK_THIS,
        TOK_RETURN,
        TOK_CONTINUE,
        TOK_BREAK,
        TOK_EXIT,
        TOK_TRY,
        TOK_CATCH,
        TOK_THROW,
        TOK_SWITCH,
        TOK_CASE,
        TOK_DEFAULT,
        TOK_INCLUDE,
        TOK_EXCLUDE,
        TOK_IS,
        TOK_IN,
        TOK_IF,
        TOK_ELSE,
        TOK_FOR,
        TOK_FOREACH,
        TOK_WHILE,
        TOK_DO,
        TOK_IDENTIFIER,
        TOK_EQUALS,
        TOK_LIB_ACESSOR_OP,
        TOK_ELLIPSIS,
        TOK_LEFT_CURLY,
        TOK_RIGHT_CURLY,
        TOK_LEFT_BRACKET,
        TOK_RIGHT_BRACKET,
        TOK_LEFT_BRACE,
        TOK_RIGHT_BRACE,
        TOK_COMMA,
        TOK_DOT,
        TOK_SEMICOLON,
        TOK_COLON,
        TOK_QMARK,
        TOK_DSIGN,
        TOK_BITWISE_OR,
        TOK_BITWISE_XOR,
        TOK_BITWISE_AND,
        TOK_BITWISE_SHIFT,
        TOK_COMMENT,
        TOK_ERROR,
        TOK_EOF,
        TOK_SIZE
    };

    const std::unordered_map<LexTokenType, std::string> TOKEN_IMAGE = {
        {TOK_BOOL_LITERAL, "<bool literal>"},
        {TOK_INT_LITERAL, "<int literal>"},
        {TOK_FLOAT_LITERAL, "<float literal>"},
        {TOK_CHAR_LITERAL, "<char literal>"},
        {TOK_STRING_LITERAL, "<string literal>"},
        {TOK_ADDITIVE_OP, "<additive operator>"},
        {TOK_EXPONENTIATION_OP, "<unary exponentiation operator>"},
        {TOK_INCREMENT_OP, "<unary additive operator>"},
        {TOK_MULTIPLICATIVE_OP, "<multiplicative operator>"},
        {TOK_RELATIONAL_OP, "<relational operator>"},
        {TOK_THREE_WAY_OP, "<=>"},
        {TOK_EQUALITY_OP, "<equality operator>"},
        {TOK_LOGICAL_AND_OP, "and"},
        {TOK_LOGICAL_OR_OP, "or"},
        {TOK_NOT, "not"},
        {TOK_VOID_TYPE, "void"},
        {TOK_BOOL_TYPE, "bool"},
        {TOK_INT_TYPE, "int"},
        {TOK_FLOAT_TYPE, "float"},
        {TOK_CHAR_TYPE, "char"},
        {TOK_STRING_TYPE, "string"},
        {TOK_ANY_TYPE, "any"},
        {TOK_FUNCTION_TYPE, "function"},
        {TOK_TYPEOF, "typeof"},
        {TOK_TYPEID, "typeid"},
        {TOK_REFID, "refid"},
        {TOK_USING, "using"},
        {TOK_ENUM, "enum"},
        {TOK_NAMESPACE, "namespace"},
        {TOK_CONST, "const"},
        {TOK_VAR, "var"},
        {TOK_REF, "ref"},
        {TOK_UNREF, "unref"},
        {TOK_STRUCT, "struct"},
        {TOK_FUN, "fun"},
        {TOK_NULL, "null"},
        {TOK_THIS, "this"},
        {TOK_RETURN, "return"},
        {TOK_CONTINUE, "continue"},
        {TOK_BREAK, "break"},
        {TOK_EXIT, "exit"},
        {TOK_TRY, "try"},
        {TOK_CATCH, "catch"},
        {TOK_THROW, "throw"},
        {TOK_SWITCH, "switch"},
        {TOK_CASE, "case"},
        {TOK_DEFAULT, "default"},
        {TOK_INCLUDE, "include"},
        {TOK_EXCLUDE, "exclude"},
        {TOK_IS, "is"},
        {TOK_IN, "in"},
        {TOK_IF, "if"},
        {TOK_ELSE, "else"},
        {TOK_FOR, "for"},
        {TOK_FOREACH, "foreach"},
        {TOK_WHILE, "while"},
        {TOK_DO, "do"},
        {TOK_IDENTIFIER, "identifier"},
        {TOK_EQUALS, "="},
        {TOK_LIB_ACESSOR_OP, "::"},
        {TOK_ELLIPSIS, "..."},
        {TOK_LEFT_CURLY, "{"},
        {TOK_RIGHT_CURLY, "}"},
        {TOK_LEFT_BRACKET, "("},
        {TOK_RIGHT_BRACKET, ")"},
        {TOK_LEFT_BRACE, "["},
        {TOK_RIGHT_BRACE, "]"},
        {TOK_COMMA, ","},
        {TOK_DOT, "."},
        {TOK_SEMICOLON, ";"},
        {TOK_COLON, ":"},
        {TOK_QMARK, "?"},
        {TOK_DSIGN, "$"},
        {TOK_BITWISE_OR, "|"},
        {TOK_BITWISE_XOR, "^"},
        {TOK_BITWISE_AND, "&"},
        {TOK_BITWISE_SHIFT, "<bitwise shift operator>"},
        {TOK_COMMENT, "<commentary>"},
        {TOK_ERROR, "<ERROR>"},
        {TOK_EOF, "<EOF>"}
    };

}

#endif // !TOKEN_CONSTANTS_HPP
